FROM node:18-alpine AS builder
WORKDIR /app/frontend
COPY ./frontend/package.json ./frontend/package-lock.json ./
RUN npm cache clean --force && npm ci --verbose || cat /root/.npm/_logs/*.log
COPY ./frontend/ ./
RUN npm run build

FROM nginx:stable-alpine
COPY --from=builder /app/frontend/build /usr/share/nginx/html
EXPOSE 80
CMD ["nginx", "-g", "daemon off;"]