# Generated by Django 4.2.18 on 2025-10-03 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Education',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.CharField(max_length=255)),
                ('university', models.CharField(max_length=255)),
                ('faculty', models.CharField(max_length=255)),
                ('direction', models.CharField(max_length=255)),
                ('level', models.CharField(max_length=255)),
                ('active', models.BooleanField(default=True)),
                ('create_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
