# Generated by Django 4.2.18 on 2025-10-03 11:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('payments', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Refund',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('requested', 'Запрошен'), ('processing', 'В обработке'), ('approved', 'Одобрен'), ('completed', 'Выполнен'), ('rejected', 'Отклонен'), ('failed', 'Ошибка')], default='requested', max_length=20)),
                ('reason', models.TextField(max_length=1000)),
                ('contact_info', models.CharField(blank=True, help_text='Контактные данные для связи (email, телефон, Telegram и т.д.)', max_length=255, null=True)),
                ('admin_comment', models.TextField(blank=True, max_length=1000, null=True)),
                ('keep_product', models.BooleanField(default=False, help_text='Средства возвращаются, но товар остаётся у пользователя')),
                ('is_admin_created', models.BooleanField(default=False, help_text='Оформил ли заявку админ')),
                ('requested_at', models.DateTimeField(auto_now_add=True)),
                ('processed_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('processed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='processed_refunds', to=settings.AUTH_USER_MODEL)),
                ('purchase', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='refunds', to='payments.purchasedreadytask')),
            ],
            options={
                'ordering': ['-requested_at'],
            },
        ),
        migrations.CreateModel(
            name='Files',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('path', models.TextField(blank=True, max_length=1000)),
                ('create_date', models.DateTimeField(auto_now_add=True)),
                ('refund', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='files', to='refunds.refund')),
            ],
            options={
                'verbose_name': 'Файл запроса на возврат',
                'verbose_name_plural': 'Файлы запросов на возврат',
            },
        ),
    ]
