# Generated by Django 4.2.18 on 2025-10-03 11:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ReadyTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('discipline', models.CharField(max_length=200)),
                ('type', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True, null=True)),
                ('city', models.CharField(max_length=200)),
                ('university', models.CharField(max_length=200)),
                ('faculty', models.CharField(max_length=200)),
                ('direction', models.CharField(max_length=200)),
                ('level', models.CharField(max_length=200)),
                ('tutor', models.CharField(max_length=200)),
                ('score', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('price', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('create_date', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('active', 'Активно'), ('unpublished', 'Снято с публикации'), ('review', 'На проверке')], default='review', max_length=20)),
                ('views', models.PositiveIntegerField(default=0)),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('previous_version', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='new_versions', to='ready_tasks.readytask')),
            ],
        ),
        migrations.CreateModel(
            name='PlacementPackage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_slots', models.PositiveIntegerField(help_text='Общее количество мест для размешения')),
                ('used_slots', models.PositiveIntegerField(default=0, help_text='Сколько мест уже использовано')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='placement_packages', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Пакет мест',
                'verbose_name_plural': 'Пакеты мест',
            },
        ),
        migrations.CreateModel(
            name='Files',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('size', models.CharField(max_length=50)),
                ('path', models.TextField(blank=True, max_length=1000)),
                ('is_public', models.BooleanField()),
                ('create_date', models.DateTimeField(auto_now_add=True)),
                ('task', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='files', to='ready_tasks.readytask')),
            ],
        ),
    ]
