# Generated by Django 4.2.18 on 2025-10-03 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Rules',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('rules', 'Правила'), ('offer', 'Оферта'), ('privacy_politic', 'Политика приватности')], max_length=20)),
                ('name', models.TextField(unique=True)),
                ('path', models.TextField(unique=True)),
                ('create_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
