# Generated by Django 4.2.18 on 2025-10-16 17:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Название задания')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Описание')),
                ('discipline', models.CharField(blank=True, max_length=200, verbose_name='Дисциплина')),
                ('type', models.CharField(blank=True, max_length=200, verbose_name='Тип работы')),
                ('city', models.CharField(blank=True, max_length=200, verbose_name='Город')),
                ('university', models.CharField(blank=True, max_length=200, verbose_name='Университет')),
                ('faculty', models.CharField(blank=True, max_length=200, verbose_name='Факультет')),
                ('direction', models.CharField(blank=True, max_length=200, verbose_name='Направление')),
                ('level', models.CharField(blank=True, max_length=200, verbose_name='Уровень подготовки')),
                ('tutor', models.CharField(blank=True, max_length=200, verbose_name='Преподаватель')),
                ('price', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Бюджет')),
                ('deadline', models.DateTimeField(blank=True, null=True, verbose_name='Дедлайн')),
                ('publish_date', models.DateTimeField(auto_now_add=True, verbose_name='Дата публикации')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Последнее обновление')),
                ('status', models.CharField(choices=[('active', 'Активно'), ('in_progress', 'В работе'), ('completed', 'Выполнено'), ('cancelled', 'Отменено'), ('unpublished', 'Снято с публикации')], default='review', max_length=20)),
                ('views', models.PositiveIntegerField(default=0)),
                ('executor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tasks_taken', to=settings.AUTH_USER_MODEL, verbose_name='Исполнитель')),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Задание',
                'verbose_name_plural': 'Задания',
                'ordering': ['-publish_date'],
            },
        ),
        migrations.CreateModel(
            name='Files',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('size', models.CharField(max_length=50)),
                ('path', models.TextField(blank=True, max_length=1000)),
                ('is_public', models.BooleanField()),
                ('create_date', models.DateTimeField(auto_now_add=True)),
                ('task', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='files', to='order_tasks.ordertask')),
            ],
        ),
    ]
