# Generated by Django 4.2.18 on 2025-10-17 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order_tasks', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ordertask',
            name='status',
            field=models.CharField(choices=[('active', 'Активно'), ('in_progress', 'В работе'), ('completed', 'Выполнено'), ('cancelled', 'Отменено'), ('review', 'На проверке'), ('unpublished', 'Снято с публикации')], default='review', max_length=20),
        ),
    ]
