# Generated by Django 4.2.18 on 2025-10-03 11:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('ready_tasks', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bank',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True, verbose_name='Название банка')),
                ('bank_id', models.CharField(max_length=50, unique=True, verbose_name='Идентификатор банка в Jump Finance')),
            ],
            options={
                'verbose_name': 'Банк',
                'verbose_name_plural': 'Банки',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='SlotPackage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slots_count', models.PositiveIntegerField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('old_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('description', models.CharField(blank=True, max_length=255)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['slots_count'],
            },
        ),
        migrations.CreateModel(
            name='Wallet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('balance', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('frozen', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='wallet', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('external_id', models.TextField(default='studium_none')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('type', models.CharField(choices=[('deposit', 'Пополнение'), ('withdraw', 'Вывод'), ('purchase_ready_task', 'Покупка работы'), ('purchase_slots', 'Покупка слотов'), ('refund', 'Возврат'), ('reward', 'Начисление за продажу')], max_length=20)),
                ('status', models.CharField(choices=[('pending', 'В исполнении'), ('frozen', 'Заморожены'), ('paid', 'Исполнена'), ('canceled', 'Отменен'), ('failed', 'Ошибка')], default='pending', help_text='Статус транзакции', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('receipt_status', models.CharField(choices=[('not_required', 'Чек не нужен'), ('pending', 'Ожидает отправки'), ('sent', 'Отправлен'), ('failed', 'Ошибка отправки')], default='not_required', help_text='Статус отправки чека', max_length=20)),
                ('wallet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='payments.wallet')),
            ],
        ),
        migrations.CreateModel(
            name='SlotsPurchase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'В ожидании оплаты'), ('paid', 'Оплачен'), ('canceled', 'Отменен'), ('refunded', 'Возвращен')], default='pending', help_text='Статус покупки', max_length=20)),
                ('count_slots', models.PositiveIntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Время создания записи покупки')),
                ('transaction', models.ForeignKey(help_text='Транзакция покупки', on_delete=django.db.models.deletion.CASCADE, related_name='purchases_slots', to='payments.transaction')),
            ],
            options={
                'verbose_name': 'Покупка слотов',
                'verbose_name_plural': 'Покупки слотов',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PurchasedReadyTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'В ожидании оплаты'), ('paid', 'Оплачен'), ('canceled', 'Отменен'), ('refunded', 'Возвращен')], default='pending', help_text='Статус покупки', max_length=20)),
                ('payment_amount', models.DecimalField(decimal_places=2, help_text='Сумма которую заплатил покупатель', max_digits=12)),
                ('commission', models.DecimalField(decimal_places=2, default=0, help_text='Сумма удержанной комиссии', max_digits=12)),
                ('net_amount', models.DecimalField(decimal_places=2, default=0, help_text='Чистая сумма, зачисляемая продавцу', max_digits=12)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Время создания записи покупки')),
                ('is_gift', models.BooleanField(default=False, help_text='Товар остается у пользователя как подарок при возврате')),
                ('buyer_transaction', models.ForeignKey(help_text='Транзакция покупки для покупателя', on_delete=django.db.models.deletion.CASCADE, related_name='buyer_purchases', to='payments.transaction')),
                ('ready_task', models.ForeignKey(help_text='Приобретённая работа', on_delete=django.db.models.deletion.CASCADE, related_name='purchases', to='ready_tasks.readytask')),
                ('refund_buyer_transaction', models.ForeignKey(blank=True, help_text='Транзакция возврата, если была', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='buyer_refund', to='payments.transaction')),
                ('refund_seller_transaction', models.ForeignKey(blank=True, help_text='Транзакция возврата, если была', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='seller_refund', to='payments.transaction')),
                ('seller_transaction', models.ForeignKey(help_text='Транзакция покупки для продавца', on_delete=django.db.models.deletion.CASCADE, related_name='seller_purchases', to='payments.transaction')),
            ],
            options={
                'verbose_name': 'Покупка работы',
                'verbose_name_plural': 'Покупки работ',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='FrozenFunds',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('reason', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('release_at', models.DateTimeField()),
                ('status', models.CharField(choices=[('frozen', 'Заморожено'), ('released', 'Разблокировано и переведено'), ('cancelled', 'Отменено, возвращено отправителю'), ('disputed', 'Спор, временно заморожено')], default='frozen', max_length=10)),
                ('transaction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='frozen_funds', to='payments.transaction')),
                ('wallet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions_funds', to='payments.wallet')),
            ],
            options={
                'verbose_name': 'Замороженные средства',
                'verbose_name_plural': 'Замороженные средства',
                'ordering': ['-created_at'],
            },
        ),
    ]
