# Generated by Django 4.2.18 on 2025-10-08 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='is_admin_seller_account',
            field=models.BooleanField(default=False, help_text='Это аккаунт админа для продажи'),
        ),
    ]
